dist: xenial

os:
    - linux
#    - osx 
#    - windows #No python support

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
        - BL_ADDON=io_scene_lwo
    matrix:
        - BLENDER_VERSION="2.90"
        - BLENDER_VERSION="2.83"
        - BLENDER_VERSION="2.82a"
        - BLENDER_VERSION="2.81a"
        - BLENDER_VERSION="2.80"
        - BLENDER_VERSION="2.79b"
        - BLENDER_VERSION="2.78c"

language: python
python:
    - 3.7

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}

addons:
    apt:
        packages:
            - blender

git:
    submodules:
        false

before_install:
    - if [[ ! -z "${GITHUB_PASSWORD}" ]]; then
        echo -e "machine github.com\n  login douglaskastle\n  password $GITHUB_PASSWORD" > ~/.netrc ;
        git submodule update --init --recursive ;
        git submodule update --remote ;
      fi
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}
#     - if [[ ! -z "${GITHUB_PASSWORD}" ]]; then
#         pip install -r scripts/requirements.txt --upgrade
#       fi

install:
    - cd $TRAVIS_BUILD_DIR
    - pip install -r blender_requirements.txt
    - pip list

script:
    - cd ${TRAVIS_BUILD_DIR}
    #- make flake8
    - python ${TRAVIS_BUILD_DIR}/scripts/test_addon.py ${BL_ADDON} ${BLENDER_VERSION}
    
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        on_success: change
        on_failure: always
