dist: xenial

os:
    - linux
#    - osx 
#    - windows #No python support

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
    matrix:
        - BLENDER_VERSION="2.78c"
        - BLENDER_VERSION="2.79b"
        - BLENDER_VERSION="2.80"
        - BLENDER_VERSION="2.81a"
        - BLENDER_VERSION="2.82"
        - BLENDER_VERSION="2.83"

language: python
python:
    - 3.7

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}

addons:
    apt:
        packages:
            - blender

git:
    submodules:
        false

before_install:
    - if [[ ! -z "${GITHUB_PASSWORD}" ]]; then
        echo -e "machine github.com\n  login douglaskastle\n  password $GITHUB_PASSWORD" > ~/.netrc ;
        git submodule update --init --recursive ;
        git submodule update --remote ;
      fi
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}
    - pip3 install -r scripts/requirements.txt --upgrade
    - yolk -l

install:
    - cd $TRAVIS_BUILD_DIR
    - python3 --version
    - python3 scripts/get_blender.py ${BLENDER_VERSION}

script:
    - cd ${TRAVIS_BUILD_DIR}
    #- ../blender-${BLENDER_VERSION}/blender --version
    #- make BLENDER_VERSION=${BLENDER_VERSION}
    - make flake8
    - python3 scripts/run_blender.py ${BLENDER_VERSION}
    - bash <(curl -s https://codecov.io/bash)

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
